# ----------------------------------------
# Kafka StatefulSet (Bitnami with KRaft mode)
# ----------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: secureevent
  labels:
    app: kafka
spec:
  serviceName: kafka                     # Required for stable network ID for each pod (via headless service)
  replicas: 1                            # One Kafka broker for now
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest    # Using Bitnami Kafka image
          ports:
            - containerPort: 9092        # Client communication port
              name: kafka
            - containerPort: 9093        # Controller communication port (KRaft mode)
              name: controller
          env:                           # Kafka configuration via environment variables
            - name: BITNAMI_DEBUG
              value: "true"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.secureevent.svc.cluster.local:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LOG_DIRS
              value: "/bitnami/kafka/data"             # Data directory
            - name: KAFKA_CFG_METADATA_LOG_DIR
              value: "/bitnami/kafka/kraft-metadata"   # Metadata directory
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka                 # Persistent mount location
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]                 # Can only be mounted on one node
        resources:
          requests:
            storage: 10Gi                              # Storage request for Kafka data

---
# ----------------------------------------
# Kafka Internal Service (ClusterIP)
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: secureevent
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: controller
  selector:
    app: kafka
  type: ClusterIP                                    # Internal service for Kafka clients inside the cluster

---
# ----------------------------------------
# Kafka Headless Service (needed for StatefulSet)
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: secureevent
  labels:
    app: kafka
spec:
  clusterIP: None                                    # Headless service — essential for StatefulSets
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: controller
  selector:
    app: kafka

---
# ----------------------------------------
# Kafka UI Service (NodePort for external access)
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: secureevent
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: NodePort                                   # Exposes the UI on a random port on all nodes

---
# ----------------------------------------
# Kafka UI Deployment (Provectus Kafka-UI)
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: secureevent
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest       # Kafka UI image by Provectus
          ports:
            - containerPort: 8080                    # UI served on port 8080
          env:                                       # Kafka cluster connection details
            - name: KAFKA_CLUSTERS_0_NAME
              value: "secureevent-cluster"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka.secureevent.svc.cluster.local:9092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
