apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: secureevent
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE
              value: devdb
